### PR TITLE
Update directory.csv

### PR DESCRIPTION
**Pull request by jc-sdev**

### CODE REVIEW

**Comment by jc-sdev** [comment]
Hello,

Will my request be processed?
Thank you

**Comment by akbargumbira** [comment]
cc @ismailsunni if you can take a look and review the PR?

**Comment by haubourg** [comment]
Hi @jc-sdev , thanks for sharing your symbols. A small description of those symbols and why you want to add them  in your PR and a basic "hello" would have been appreciated. We are all benevolent here, any help in reviewing changes are always appreciated.

**Comment by ismailsunni** [comment]
hi @jc-sdev 
first of all, thank you for your contribution. I started the review last week, but couldn't finish it. Here is the item that needs changes in the `metadata.ini`:
- the `collections=water and sanitation` should be a list with commas separated. e.g.: `collections=water,sanitation` (mandatory)

**Comment by jc-sdev** [comment]
cc @ismailsunni 

I did the metadata modification and hope it will be good

Thanks

JC

**Comment by jc-sdev** [comment]
Hello haubourg

I'm sorry I didn't give you a little introduction and welcome but I've been struggling to update the directory. 
I'm still not comfortable enough with the way github works.

jc

**Comment by ismailsunni** [comment]
Hi @jc-sdev 
thanks for the update. There is one more issue, please use `master` as the default branch. Unfortunately, it's a known limitation.

**Comment by jc-sdev** [comment]
hi ismailsunni
I think I've got it this time 
thanks
jc

**Comment by ismailsunni** [comment]
Many thanks @jc-sdev :+1:

**Pull request merged**
