### PR TITLE
Update directory.csv

### PR DESCRIPTION
**Pull request by ludovico85**
Here is my small contribution. If you want, add me. Thank you.

### CODE REVIEW

**Comment by ismailsunni** [comment]
Hi @ludovico85 thanks for your contributions. I tried to install your repository, and found an issue:

1. Could you change your default branch to `master`? Unfortunately, this is still a known issue https://github.com/QGIS-Contribution/QGIS-ResourceSharing/issues/286

**Comment by ludovico85** [comment]
> Hi @ludovico85 thanks for your contributions. I tried to install your repository, and found an issue:
> 
>     1. Could you change your default branch to `master`? Unfortunately, this is still a known issue [error when adding repository that has no "master" branch QGIS-Contribution/QGIS-ResourceSharing#286](https://github.com/QGIS-Contribution/QGIS-ResourceSharing/issues/286)

Hi, do you mean I should create a new pull request directly to the master branch?

**Comment by ismailsunni** [comment]
@ludovico85 no. I mean you need to create a new branch named `master` in your repository. Currently, there is only `main` branch in your repository. QGIS Resource Sharing currently only works with `master` branch.

**Comment by ludovico85** [comment]
> @ludovico85 no. I mean you need to create a new branch named `master` in your repository. Currently, there is only `main` branch in your repository. QGIS Resource Sharing currently only works with `master` branch.

Ok, Done. Thanks.

**Comment by ismailsunni** [comment]
Thanks @ludovico85 , I tested it and I can load the model (didn't run it though)

Best regards :)

**Pull request merged**
