### PR TITLE
Add repository PlanZV

### PR DESCRIPTION
**Pull request by bstroebl**

### CODE REVIEW

**Comment by akbargumbira** [comment]
@bstroebl: just a note that license is defined for each collection and should be put in the root of the collection. So in your case, the license file should be put under PlanZV directory. 

The SVGs also don't look good in the SVGs preview panel:
planzv 

Compared to Maki for example: 
maki

I am not sure right now about the SVG dimensions that will look good in that panel :) @anitagraser any idea?

**Comment by bstroebl** [comment]
> just a note that license is defined for each collection and should be put in the root of the collection. So in your case, the license file should be put under PlanZV directory. 

done, thanks for pointing it out @akbargumbira

> I am not sure right now about the SVG dimensions that will look good in that panel

I've seen that they are to be too big when I manually added the repository in the plugin. Probably I would have to make them smaller but I lived under the impression that svg is dimensionless in some way ;-)

**Comment by anitagraser** [comment]
Thanks for sharing @bstroebl! I think we can merge this but please have a look at improving the presentation in the SVG panel. It would also be great if you could add one or two preview images to your repository (similar to the Maki repo example) so the user can have a look at the content before downloading it.

**Comment by bstroebl** [comment]
Thanks for merging. @anitagraser do you have an idea how I can improve the presentation in the panel? Is it just a matter of making the graphics in the svg files smaller?
Will add a preview in the repo.

**Comment by anitagraser** [comment]
@bstroebl Sorry I don't know what causes the issue. If I had to guess, I'd have a look if the SVG "page" is actually smaller than the drawing.

**Comment by bstroebl** [comment]
There is no `page` tag in the svg but the width and height parameters seem to fit. I created all svgs with inkscape and used "fit page to drawing" to determine the page size. My svgs look very different from the maki icons (i.e. in the editor). 
For testing I made one drawing smaller (and then refittet the page). After restarting QGIS the svg chooser still shows it in the same (= only partial) way.

**Pull request merged**
