### PR TITLE
Update directory.csv

### PR DESCRIPTION
**Pull request by northrivergeo**
Adding the NPS Symbols I created from https://www.nps.gov/hfc/carto/map-symbols.cfm

### CODE REVIEW

**Comment by anitagraser** [comment]
That looks like a huge collection. That's great!

Could you please add some preview images so users can see what they are downloading from within the Ressource Sharing plugin dialog?

Also an explicit license file (similar to what we have e.g. in https://github.com/qgis/QGIS-Resources/tree/master/collections/all_maki_icons) would be great.

Thank you!

**Comment by northrivergeo** [comment]
Will do! Give me just a bit and I will get that done. Yes - it was a bit of a pain to do but I hope worth it.

**Comment by havatv** [comment]
@rjhale1971 - this one has been around for a while. Any progress with the preview(s)?

**Comment by havatv** [comment]
@anitagraser, this collection seems to be worth including. Could it be merged before the preview is available? Or could someone else do the preview? I don't think it will be trivial for me, but someone who has done similar things before could perhaps fix it quite easily?

**Comment by northrivergeo** [comment]
Hey - good morning. I'm sorry - completely forgot about these icons into resource sharing. Let me take a look at it and get it working.

**Comment by havatv** [comment]
> Hey - good morning. I'm sorry - completely forgot about these icons into resource sharing. Let me take a look at it and get it working.

Excellent!

**Comment by northrivergeo** [comment]
So I've added preview images - and pushed it all up. I'm not sure what to do next on this (since it's been so long).

**Comment by havatv** [comment]
@rjhale1971, I have just tested the repository. An impressive collection - thank you for sharing!
There were some issues with the metadata.ini file.  I have fixed them in a pull request against your repository (https://github.com/rjhale1971/NPS_Map_Symbols/pull/1).  As soon as that pull request is merged, I think this is ready for inclusion. Then, we can ask @anitagraser to do the rest (merge).

**Comment by havatv** [comment]
@rjhale1971 has now merged https://github.com/rjhale1971/NPS_Map_Symbols/pull/1, and I was able to add the repository and install collections from it.  So this PR should be ready for merging.
What do you say, @anitagraser?

**Comment by havatv** [comment]
Thanks, @anitagraser!
And thanks again for sharing, @rjhale1971!

**Pull request merged**
