### PR TITLE
added PISM QGIS resource repo

### PR DESCRIPTION
**Pull request by aaschwanden**
(currently small) set of styles used for visualizing ice sheet modeling results.

### CODE REVIEW

**Comment by anitagraser** [comment]
Hi Andy, thanks for sharing your styles! Could you please add license information and a preview to the collection so users can see what they are downloading? Best wishes

**Comment by aaschwanden** [comment]
Hi Anita,

yes, sure I'd be happy to do that. Might take a week or two since I'm
heading to a meeting.

Andy

**Comment by anitagraser** [comment]
Hi Andy, do you still plan to work on this or should I close this PR?

**Comment by pcav** [comment]
IMHO it would be a pity to miss it. Andy, may I ask you to do a little extra effort?
Thanks.

**Comment by aaschwanden** [comment]
Hi,

sorry for the delay.

I’ve just added a license file and a preview and committed the changes.

I know my collection is still very small, but I keep adding styles whenever I deem a style good enough for me to use in a scientific publication.

The QGIS-resources and resource sharing plugins are very useful, and I’m still trying to convince my collaborators to use them…

Andy

**Pull request merged**
