### PR TITLE
Faunalia Style Repository

### PR DESCRIPTION
**Pull request by ghtmtt**
Addition to the csv file in order to add Faunalia repository

### CODE REVIEW

**Comment by anitagraser** [comment]
Thanks for sharing Matteo!

**Comment by ghtmtt** [comment]
Thanks Anita for merging this. The repository is available as an official repo, but the name (in my case) is matteo, while in the dictionary.csv the name is Faunalia.

Thanks for all the suggestions!
 
selection_013

**Comment by anitagraser** [comment]
Looks fine on my machine. Could you have another look on a different computer? Could it be that you added your repo manually at some point?

**Comment by ghtmtt** [comment]
Yes, yesterday I added the repo manually with the name matteo.. I tried now with the `--configpath` option and it look OK! So just something related to my machine, sorry for the noise. Thanks for verifying this!

**Pull request merged**
