### PR TITLE
Include the QGIS 2 R script on-line collection in the repository

### PR DESCRIPTION
**Pull request by havatv**
The scripts are copied from https://github.com/qgis/QGIS-Processing/tree/master/rscripts.

By having them here, the user can install the script using the QGIS Resource Sharing plugin. With the current version of the plugin, the installation will be in the folder  ``<QGIS user folder>/resource_sharing/repositories/github.com/qgis/QGIS-Resources/collections/rscripts``, and ``R scripts folder`` will have to be modified.

I have provided a description of how to get the R scripts (from a test repository) installed by the plugin to show up in the Processing Toolbox in:
https://gis.stackexchange.com/a/348772/22646
It works for the test repository setup. I assume that changing the directory "structure" (changing the name of the "destination" folder to ``rscript`` and moving it up to the "top level") will not cause problems for the QGIS Resource Sharing plugin (have not tested).

### CODE REVIEW

**Comment by anitagraser** [comment]
Thanks for sharing, Håvard!

**Comment by havatv** [comment]
Thanks you for your huge work for the QGIS community, Anita!

I was wondering if the rscripts directory should be place in the processing directory or not (in this PR it was not in the processing directory). I have no preferences.
What is your opinion? (I can move the directory if you like)

**Comment by anitagraser** [comment]
We can move it if someone raises an issue. For now, let's keep it as is.

**Comment by ghtmtt** [comment]
Thanks @havatv! That's a great move.

**Comment by havatv** [comment]
> We can move it if someone raises an issue. For now, let's keep it as is.

Thanks.
We can move it if it will help getting rscript resources more tightly integrated through the resource sharing plugin...
I will use the current location when updating the documentation (working on it now).

**Pull request merged**
