### PR TITLE
Add nautical symbols for marine charts

### PR DESCRIPTION
**Pull request by francoisatilio**
I propose the nautical symbols for marine charts i'm using and sharing in my blog (www.sigterritoires.fr)

Regards

Atilio FRANCOIS

### CODE REVIEW

**Comment by akbargumbira** [comment]
Thanks @francoisatilio, it seems good for me +1. Just a note that since you're using zip handler, the extracted zip should be the collection itself (svg, processing, image directories), not a root directory (in your case named nautilus). But since you only have svg on the collection, it is fine. Are you planning to add e.g style or symbol?

**Comment by francoisatilio** [comment]
Hi

I don't plan to add  other things for the miment, but I replace the 
nautical.zip file. Now it's the collection (in this case just a svg 
directory).

Regards

Atilio

**Comment by anitagraser** [comment]
Thank you for sharing your resources! 

Maybe I missed it, but in case there is none, please add a license file.

**Comment by francoisatilio** [comment]
done

regards

Atilio FRANCOIS

**Comment by anitagraser** [comment]
@akbargumbira I don't see the license file in the download folder (when pressing Open folder, it only contains an svg folder). Am I looking in the wrong place?

**Comment by francoisatilio** [comment]
Sorry

I put it beside the zip file. I'll put it inside.

Atilio FRANCOIS

**Comment by anitagraser** [comment]
Ok, thanks a lot!

**Comment by francoisatilio** [comment]
Done

Atilio FRANCOIS

**Comment by anitagraser** [comment]
http://www.nasca.ovh/downloads/nautical/collections/nautical.zip is still serving me a ZIP without license file. Some cache?

**Comment by francoisatilio** [comment]
yes, i just tried and nautical.zip has the license file

**Comment by francoisatilio** [comment]
sorry but you must wait until the host cache from ovh update the cache...

Atilio FRANCOIS

**Comment by akbargumbira** [comment]
@francoisatilio it seems that your server is down?

**Comment by akbargumbira** [comment]
hmm, now it's fine!

**Pull request merged**
