### PR TITLE
Changed directory.csv

### PR DESCRIPTION
**Pull request by mara91**
Adding Swedish styling for "Berggrundsytor"

### CODE REVIEW

**Comment by anitagraser** [comment]
Dear Mara, 
Thank you for sharing your style! Could you please add a description in English to the metadata? Feel free to keep Swedish and English but in the official repo, we need to think about all our users.

**Comment by mara91** [comment]
Hi!
I changed the "metadata.ini"-file to an english description. Is that what you meant?

**Comment by anitagraser** [comment]
Yes, that's what I meant. Thank you!

**Comment by mara91** [comment]
How nice! I love the idea of "Resource sharing" and will continue to contribute with more styles!

**Comment by anitagraser** [comment]
That's great! Is the layer "Berggrundsytor" open data? Can you provide a link for testing the QML?

**Comment by mara91** [comment]
Yes, the layer "Berggrundsytor" is open data.

**Comment by mara91** [comment]
What do you mean with the second question? What kind of link?

**Comment by anitagraser** [comment]
Sorry, I would like to download the dataset. Can you tell me where to find it?

**Comment by mara91** [comment]
I see!

This is the link: http://www.sgu.se/produkter/geologiska-data/vara-data-per-amnesomrade/berggrundsgeologiska-data/berggrund-11-miljon/

**Comment by mara91** [comment]
And to get the data you click on "Komprimerad fil med berggrundskartan i shape-format."

**Comment by mara91** [comment]
Hi! I've done som changes in my repository. Does it change automatically or do I have to pull again?

**Comment by anitagraser** [comment]
As long as the URL does not change, you don't need to do anything here.

**Pull request merged**
