### PR TITLE
Add HERE icons

### PR DESCRIPTION
**Pull request by cedricr**
Added my repackaging of the HERE icons (original: https://github.com/heremaps/here-icons)

### CODE REVIEW

**Comment by ismailsunni** [comment]
Dear @cedricr 
Thanks for your contribution.

Could you add some tags on the https://github.com/cedricr/here-icons-qgis/blob/master/metadata.ini#L12? After that, we can merge it. Awesome resource!

**Comment by cedricr** [comment]
Thank you @ismailsunni !
I've updated the icons from the latest upstream changes, added the tags and solved the merge conflicts from this branch. Let me know if there's something else I should do!

**Comment by ismailsunni** [comment]
All looks good @cedricr, thanks for updating it. I will merge it.

**Comment by cedricr** [comment]
Thanks @ismailsunni !

**Pull request merged**
