### PR TITLE
Faunalia repo url edited

### PR DESCRIPTION
**Pull request by ghtmtt**
The Faunalia git repository is changed. No big changes, just the url.
Sorry for the noise again

### CODE REVIEW

**Comment by ghtmtt** [comment]
@anitagraser 
Hi! Sorry for ping again.. Can we merge this PR?

**Comment by timlinux** [comment]
Hi @ghtmtt - I will merge it for you - thanks!

**Comment by ghtmtt** [comment]
thanks @timlinux

**Comment by anitagraser** [comment]
Thanks @timlinux for stepping in. Was offline for a few days.

**Pull request merged**
