### PR TITLE
Update directory.csv

### PR DESCRIPTION
**Pull request by lequynhhoa**
Update style forest national Vietnam (KKR)

### CODE REVIEW

**Comment by anitagraser** [comment]
Thank you for sharing!

To add your collection to the official repository, please add a license file and one or more preview images. For an example, please see https://github.com/anitagraser/QGIS-resource-collections/tree/master/collections/arrows

**Comment by lequynhhoa** [comment]
Thank you, but I have a question, how is make license file?

**Comment by akbargumbira** [comment]
Hi @lequynhhoa, you can specify the license (and optionally the license file as follows):
* In metadata.ini, add ```license``` and ```license_file``` (optional) entry, for example:
```
license=This collection is released under CC0.
license_file=LICENSE.txt
````
* If you specify the license_file, put LICENSE.txt under ```collections/kkr``` directory.

**Review by havatv — APPROVED** [review]
Thanks for sharing, l2equynhhoa!
Looks fine syntactically.

Ihav not yet been able to check the repo.

**Review by havatv — COMMENTED** [review]
i have problrms  installing the voollection, and I can't find the CSVs in the reository.Could you chechthe repo structure and metadata syntax/contents?

**Comment by ismailsunni** [comment]
I will close this one as it seems already superseded by #36

**Pull request closed without merging**
